name: "MikroTik Country Address List"

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '*/15 * * * *'

jobs:
  runscript:
    name: GetIP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@main

      - name: Call a Bash Script
        run: |
          bash get.sh > Iran-Address-List.rsc
          git config --global user.email "16175284+MrNetwork@users.noreply.github.com"
          git config --global user.name "MrNetwork"
          git config credential.helper store
          git add -A
          git diff-index --quiet HEAD || git commit -m "Automatic update"
          git push -f
