
name: MikroTik Country Address List
on: repository_dispatch
jobs:
    resources:
        name: Update resources
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - uses: actions/setup-node@v1

            - name: Fetch resources
              run: ./getip.sh

            - name: Update resources
              uses: test-room-7/action-update-file@v1
              with:
                  file-path: ./Iran-Address-List.rsc
                  commit-msg: Update resources
                  github-token: ${{ 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 }}
